language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
env:
- PLONE_VERSION=4.2
- PLONE_VERSION=4.3
- PLONE_VERSION=5.0
matrix:
  fast_finish: true
install:
- sed -ie "s#test-5.0#test-$PLONE_VERSION#" buildout.cfg
- test "$PLONE_VERSION" = "5.0" && sed -ie "s#test-eggs =#test-eggs = plone.app.contenttypes#" buildout.cfg || true
- python bootstrap.py
- bin/buildout annotate
- bin/buildout -Nq
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
- bin/code-analysis
- bin/test
after_success:
- bin/createcoverage
- pip install -q coveralls
- coveralls
notifications:
  irc: irc.freenode.org#plone-testing
